=== Aleexm7/Lenguajes_de_Marca/DTD/Ejercicio9DTD.dtd
<!ELEMENT personas (persona*, provincias)>
<!ELEMENT persona (nombre, nacimiento?, direccion+)>
    <!ATTLIST persona sexo (H | M | N) #REQUIRED>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT nacimiento EMPTY>
  <!ATTLIST nacimiento
        anyo CDATA #REQUIRED
        mes CDATA #REQUIRED
        dia CDATA #REQUIRED>
    <!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
      <!ELEMENT calle (#PCDATA)>
      <!ELEMENT poblacion (#PCDATA)>
        <!ATTLIST poblacion prov IDREF #REQUIRED>
      <!ELEMENT cpostal (#PCDATA)>
        
        
<!ELEMENT provincias (provincia*)>
  <!ELEMENT provincia (#PCDATA)>
      <!ATTLIST provincia idProv ID #REQUIRED>

=== Aleexm7/Lenguajes_de_Marca/DTD/Ejercicio9DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE personas SYSTEM "Ejercicio9DTD.dtd">

<personas>
  <persona sexo="H">
    <nombre>Paco</nombre>
    <nacimiento anyo="1986" mes="3" dia="5"/>
    <direccion>
      <calle>caoba 1</calle>
      <poblacion prov="p41">camas</poblacion>
      <cpostal>41005</cpostal>
    </direccion>
  </persona>
  
  <persona sexo="M">
    <nombre>Juanita</nombre>
    <nacimiento anyo="1999" mes="2" dia="5"/>
    <direccion>
      <calle>Altamira 1</calle>
      <poblacion prov="p34">inventada</poblacion>
      <cpostal>34005</cpostal>
    </direccion>
  </persona>
  <provincias>
  <provincia idProv="p41">Sevilla</provincia>
  <provincia idProv="p34">Palencia</provincia>
  </provincias>

</personas>
