<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE productos [
   <!ELEMENT productos (producto)*>
   <!ELEMENT producto (identificacion, nombre?)>
   <!ELEMENT identificacion (codigo | id)*>
   <!ELEMENT codigo (#PCDATA)>
   <!ELEMENT id (#PCDATA)>
   <!ELEMENT nombre (#PCDATA)>
]>

<productos>
<producto>
   <identificacion>
      <codigo>TAL264MA</codigo>
      <id>34890</id>
      </identificacion>
</producto>
<producto>
<!-- El elemento nombre aparece antes que identificación, tendremos que cambiar el orden-->
   <identificacion>
      <codigo>MAR321</codigo>
      <id>678984</id>
      <codigo>MAN90</codigo>
      <id>610988</id>
    </identificacion>
    <nombre>Recolectora</nombre>
</producto>
<producto>
<!-- El elemento nombre aparece dentro del elemento identificacion, hay que sacarlo de ese elemento y ponerlo en el orden correcto -->
   <identificacion>
      <codigo>ATT098P</codigo>
      <id>61900</id>
      </identificacion>
      <nombre>Ordenador</nombre>
</producto>
</productos>