=== Aleexm7/Lenguajes_de_Marca/DTD/Ejercicio7DTD.dtd
<!ELEMENT ediciones (cabecera, tabla)>
  <!ELEMENT cabecera (titulo, contenido, descripcion)*>
    <!ATTLIST cabecera fecha CDATA #REQUIRED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT contenido (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    
  <!ELEMENT tabla (norte, centro, sur)>
    <!ELEMENT norte (nombre,trimestre*)>
      <!ELEMENT nombre (#PCDATA)>
      <!ELEMENT trimestre EMPTY>
          <!ATTLIST trimestre numero CDDATA #REQUIRED>
          <!ATTLIST trimestre lib_vendidos CDDATA #REQUIRED>
      
    <!ELEMENT centro (trimestre,lib_vendidos)*>
     <!ELEMENT centro (nombre,trimestre*)>
      <!ELEMENT nombre (#PCDATA)>
      <!ELEMENT trimestre EMPTY>
          <!ATTLIST trimestre numero CDDATA #REQUIRED>
          <!ATTLIST trimestre lib_vendidos CDDATA #REQUIRED>
          
    <!ELEMENT sur (trimestre, lib_vendidos)*>
       <!ELEMENT sur (nombre,trimestre*)>
      <!ELEMENT nombre (#PCDATA)>
      <!ELEMENT trimestre EMPTY>
          <!ATTLIST trimestre numero CDDATA #REQUIRED>
          <!ATTLIST trimestre lib_vendidos CDDATA #REQUIRED>

=== Aleexm7/Lenguajes_de_Marca/DTD/Ejercicio7DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ediciones SYSTEM "Ejercicio7DTD.dtd">
<ediciones>
  <cabecera fecha="30/12/2009">
    <titulo>Ediciones</titulo>
    <contenido>Informe regional de ventas</contenido>
    <descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</descripcion>
  </cabecera>
  <tabla>
      <norte>
        <nombre>Norte</nombre>
        <trimestre numero="1" lib_vendidos="2400"/>
        <trimestre numero="2" lib_vendidos="38600"/>
        <trimestre numero="3" lib_vendidos="NO_INFO"/>
        <trimestre numero="4" lib_vendidos="NO_INFO"/>
      </norte>
      <centro>
        <nombre>Centro</nombre>
        <trimestre numero="1" lib_vendidos="NO_INFO"/>
        <trimestre numero="2" lib_vendidos="16080"/>
        <trimestre numero="3" lib_vendidos="2500"/>
        <trimestre numero="4" lib_vendidos="2900"/>
      </centro>
      <sur>
        <nombre>Sur</nombre>
        <trimestre numero="1" lib_vendidos="2700"/>
        <trimestre numero="2" lib_vendidos="31400"/>
        <trimestre numero="3" lib_vendidos="40400"/>
        <trimestre numero="4" lib_vendidos="30000"/>
      </sur>
  </tabla>
</ediciones>
