=== Aleexm7/Lenguajes_de_Marca/Schema XML/Ejercicio10Schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="aeropuerto">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">  
        <xs:element type="xs:string" name="nombre"/> 
        <xs:element type="xs:date" name="fecha"/>
        <xs:element name="vuelos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vuelo" maxOccurs="unbounded" minOccurs="0"> 
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="diario" type="tipoVacio" minOccurs="0" maxOccurs="1"/> 
                    <xs:element type="xs:string" name="origen"/>
                    <xs:element type="xs:string" name="destino"/>    
                    <xs:element type="xs:time" name="hora-salida"/>
                    <xs:element type="xs:time" name="hora-llegada"/>
                  </xs:sequence>
                  <xs:attribute name="cÃ³digo" type="xs:ID" use="required"/> 
                  <xs:attribute name="estado" use="optional" default="E">  
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="[CER]" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>



  <xs:simpleType name="tipoVacio">    
    <xs:restriction base="xs:string">
      <xs:length value="0"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Aleexm7/Lenguajes_de_Marca/Schema XML/Ejercicio10Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<aeropuerto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio10Schema.xsd">

   <fecha>2013-12-20</fecha>  <!-- Cambio el orden de las etiquetas-->

   <nombre>JFK</nombre>
   
   <vuelos>
      <vuelo código="V22" estado="R">   <!-- El atributo codigo es de tipo ID-->
         <diario />
         <origen>New York</origen>
         <destino>Chicago</destino>
         <hora-salida>09:30:00</hora-salida>
         <hora-llegada>11:30:00</hora-llegada>
      </vuelo>
      <vuelo código="V23" estado="C">    <!-- Si no se indica el estado por defecto es E-->
         <origen>New York</origen>
         <destino>Miami</destino>
         <hora-salida>10:15:00</hora-salida>
         <hora-llegada>11:15:00</hora-llegada>
      </vuelo>
   </vuelos>
</aeropuerto>
